model: IFS-FESOM 
exp: control-1990
source: lra-r100-monthly

loglevel: warning
outputdir: ./output

# nworkers: 2

variables: ["thetao", "so"]

# select_time:
#   start_year : 1991
#   end_year : 1991
 
ocean_circulation: #specify region and climatology time
  compare_model_with_obs: True
  regions:
    Labrador Sea : DJF
    Irminger Sea : DJF
    Ross Sea : JJA
    Weddell Sea : JJA
    Gin Sea : DJF
  plots:
    [
      stratification,
      MLD
    ]