model: IFS-FESOM 
exp: control-1990
source: lra-r100-monthly

loglevel: warning
outputdir: ./output

# nworkers: 2

variables: ["thetao", "so"]

# select_time:
#   start_year : 1991
#   end_year : 1991

ocean_drift:
  regions:
    - Indian Ocean
    - Atlantic Ocean
    - Arctic Ocean
    - Southern Ocean
    - Pacific Ocean
    - Global Ocean 
  plots: [
          hovmoller,
          time_series,
          multilevel_trend,
          zonal_trend
          ]

    