# Configuration file for aqua-analysis.sh

# Variables $AQUA_CORE, $AQUA_DIAGNOSTICS $AQUA_CONFIG and $OUTPUT can be used to refer to
# the directory of the AQUA-core module,
# the directory of the AQUA-diagnostics module,
# the config directory (i.e. .aqua) and the output directory respectively.

job:
    # The max_threads variable serves as a mechanism to control the maximum number of diagnostics being run concurrently
    # - If max_threads is set to 0 or a negative value: There is no limit on the number of parallel diagnostics,
    #                                                   and all processes run in parallel without waiting.
    #                                                   This is suitable for situations where you want to utilize
    #                                                   the maximum available resources without any restrictions.
    # - If max_threads is set to a positive value: It limits the number of concurrent processes to the specified value.
    #                                              After launching the designated number of diagnostics, the script waits
    #                                              for these to complete before launching additional ones.
    #                                              This is useful when you are working on a system with limited
    #                                              resources, such as a login node

    max_threads: 0  # Set to the desired maximum number of threads, or leave it as 0 for no limit
    loglevel: "WARNING" # DEBUG, INFO, WARNING, ERROR, CRITICAL

    # Run a check analysis to test the configuration and the presence of needed data
    # This also rebuild the area files, to avoid error with corrupted files
    run_checker: true

    # Default output directory for the analysis. Can be overridden by the command line arguments
    outputdir: "./output"

    # Default values, overriden from command line arguments
    catalog: "climatedt-gen2"  # The catalog to use for the analysis
    model: "IFS-NEMO-5km"
    exp: "baseline-hist"
    source: "lra-r100-monthly"
    regrid: null
    startdate: null
    enddate: null

    script_path_base: "${AQUA_DIAGNOSTICS}"  # Base directory for the diagnostic scripts

    experiment_kind: "${AQUA_CONFIG}/analysis/climatedt-experiment-kind.yaml"  # experiment kind file configuraton

cluster:  # options for dask cluster (this works well on lumi)
    workers: 32
    threads: 1  # per worker
    memory_limit: 7GiB  # per worker
    connect_timeout: 120  # seconds to wait for client to connect to the cluster
    # ftp_timeout: 60  # timeout in seconds for ftp connections. Will not be set if omitted.

# List of available CLI tools (diagnostics)
cli:
  biases: "biases/cli_biases.py"
  boxplots: "boxplots/cli_boxplots.py"
  drift: "ocean_drift/cli_ocean_drift.py"
  ecmean: "ecmean/cli_ecmean.py"
  enso: "teleconnections/cli_teleconnections.py"
  gregory: "timeseries/cli_timeseries.py"
  histogram: "histogram/cli_histogram.py"
  lat_lon_profiles: "lat_lon_profiles/cli_lat_lon_profiles.py"
  nao: "teleconnections/cli_teleconnections.py"
  seaice: "seaice/cli_seaice.py"
  seasonal_cycles: "timeseries/cli_timeseries.py"  # not used
  stratification: "ocean_stratification/cli_ocean_stratification.py"
  timeseries: "timeseries/cli_timeseries.py"
  trends: "ocean_trends/cli_ocean_trends.py"

run:
    - ["ocean2d", "ocean3d-part1", "ocean3d-part2", "teleconnections-enso"]

  # List of diagnostics

  # Each diagnostic can have the following options (all optional):
  #    nworkers: the number of workers to use for the diagnostic if a global dask cluster is not used. Default is 1.
  #              Notice: these are still provided mostly for testing the local cluster option, using a global cluster (not using this option) is the new default.
  #    config: the configuration file for the diagnostic.
  #    extra: extra command line arguments to pass to the diagnostic script.
  #    outname: the name of the output directory for the diagnostic. Default is the diagnostic name itself.
  #    script_path: the location of the script to run the diagnostic.
  #                 Default script_path is "$script_path_base/$diagnostic/cli/cli_${diagnostic}.py"
  #    nocluster: boolean, if set to true, the diagnostic will not use the global dask cluster. Default is false (needed for ECmean)
diagnostics:
  atmosphere2d:
    biases:
      config: ["${AQUA_CONFIG}/collections/jinja/atmosphere2d/config-atmosphere2d-berkeley.j2",
               "${AQUA_CONFIG}/collections/jinja/atmosphere2d/config-atmosphere2d-era5.j2"]
    timeseries:
      config: ["${AQUA_CONFIG}/collections/jinja/atmosphere2d/config-atmosphere2d-berkeley.j2",
               "${AQUA_CONFIG}/collections/jinja/atmosphere2d/config-atmosphere2d-era5.j2"]
    lat_lon_profiles:
      config: "${AQUA_CONFIG}/collections/jinja/atmosphere2d/config-atmosphere2d-berkeley.j2"

  atmosphere3d:
    biases:
      config: "${AQUA_CONFIG}/collections/jinja/atmosphere3d/config-atmosphere3d-era5.j2"

  climate_metrics:
    ecmean:
      config: "${AQUA_CONFIG}/collections/jinja/climate_metrics/config-climate_metrics-ecmean.j2"
      nocluster: true  # ECmean does not use the global dask cluster
      source_oce: true  # if a --source_oce argument was passed use it
    gregory:
      config: "${AQUA_CONFIG}/collections/jinja/climate_metrics/config-climate_metrics-gregory.j2"

  ocean2d:
    biases:
      config: "${AQUA_CONFIG}/collections/jinja/ocean2d/config-ocean2d-esacci.j2"
    timeseries:
      config: "${AQUA_CONFIG}/collections/jinja/ocean2d/config-ocean2d-esacci.j2"
    lat_lon_profiles:
      config: "${AQUA_CONFIG}/collections/jinja/ocean2d/config-ocean2d-esacci.j2"

  ocean3d-part1:
    trends:
      config: "${AQUA_CONFIG}/collections/jinja/ocean3d/config-ocean3d-en4-trend-drift.j2"  # these diagnostics need a different chunking
      outname: "ocean3d"
    drift:
      config: "${AQUA_CONFIG}/collections/jinja/ocean3d/config-ocean3d-en4-trend-drift.j2"  # these diagnostics need a different chunking
      outname: "ocean3d"

  ocean3d-part2:
    stratification:
      config: "${AQUA_CONFIG}/collections/jinja/ocean3d/config-ocean3d-en4-stratification.j2"
      outname: "ocean3d"

  radiation-toa:
    biases:
      config: "${AQUA_CONFIG}/collections/jinja/radiation_toa/config-radiation_toa-ceres.j2"
    boxplots:
      config: "${AQUA_CONFIG}/collections/jinja/radiation_toa/config-radiation_toa-boxplots.j2"
    timeseries:
      config: "${AQUA_CONFIG}/collections/jinja/radiation_toa/config-radiation_toa-ceres.j2"

  radiation-surface:
    biases:
      config: ["${AQUA_CONFIG}/collections/jinja/radiation_surface/config-radiation_surface-ceres.j2",
               "${AQUA_CONFIG}/collections/jinja/radiation_surface/config-radiation_surface-era5.j2"]
    boxplots:
      config: "${AQUA_CONFIG}/collections/jinja/radiation_surface/config-radiation_surface-boxplots.j2"
    timeseries:
      config: ["${AQUA_CONFIG}/collections/jinja/radiation_surface/config-radiation_surface-ceres.j2",
               "${AQUA_CONFIG}/collections/jinja/radiation_surface/config-radiation_surface-era5.j2"]

  seaice:
    seaice:
      config: ["${AQUA_CONFIG}/collections/jinja/seaice/config-seaice-osi.j2",
               "${AQUA_CONFIG}/collections/jinja/seaice/config-seaice-psc.j2"]

  teleconnections-nao:
    nao:
      config: "${AQUA_CONFIG}/collections/jinja/teleconnections/config-teleconnections-nao.j2"
      outname: "teleconnections"

  teleconnections-enso:
    enso:
      config: "${AQUA_CONFIG}/collections/jinja/teleconnections/config-teleconnections-enso.j2"
      outname: "teleconnections"

  water_cycle:
    lat_lon_profiles:
      config: "${AQUA_CONFIG}/collections/jinja/water_cycle/config-water_cycle-mswep.j2"
    timeseries:
      config: "${AQUA_CONFIG}/collections/jinja/water_cycle/config-water_cycle-mswep.j2"
    biases:
      config: "${AQUA_CONFIG}/collections/jinja/water_cycle/config-water_cycle-mswep.j2"
    histogram:
      config: "${AQUA_CONFIG}/collections/jinja/water_cycle/config-water_cycle-mswep.j2"
