# Template according to #1613
# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog
datasets:
  - catalog: null
    model: null
    exp: null
    source: 'lra-r100-monthly'
    regrid: null
  # Possible second/third/fourth datasets here, no present by default
  # - catalog: 'obs'
  #   model: 'ERA5'
  #   exp: 'era5'
  #   source: 'monthly'
  #   regrid: r100

references:
  - catalog: 'obs'
    model: 'CERES'
    exp: 'ebaf-toa41'
    source: 'monthly'
    regrid: null

output:
  outputdir: "./"
  rebuild: true
  save_pdf: true
  save_png: true
  dpi: 300
  create_catalog_entry: false

diagnostics:
  timeseries:
    run: true
    diagnostic_name: 'radiation'
    variables: ['tnlwrf', 'tnswrf']
    formulae: ['tnlwrf+tnswrf']
    center_time: false
    params:
      default:
        hourly: False
        daily: False
        monthly: False
        annual: True
        std_startdate: '20000101'
        std_enddate: '20201231'
      tnlwrf+tnswrf:
        standard_name: "net_top_radiation"
        long_name: "Net top radiation"

  gregory:
    run: true
    diagnostic_name: 'radiation'
    t2m: '2t'
    net_toa_name: 'tnlwrf+tnswrf'
    monthly: true
    annual: true
    std: true
    std_startdate: '19900101'
    std_enddate: '20201231'
    # Gregory needs 2 datasets and do not care about the references block above
    t2m_ref: {'catalog': 'obs', 'model': 'ERA5', 'exp': 'era5', 'source': 'monthly'}
    net_toa_ref: {'catalog': 'obs', 'model': 'CERES', 'exp': 'ebaf-toa42', 'source': 'monthly'}
