# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog
models:
    - catalog: null
      model: 'IFS-NEMO'
      exp: 'historical-1990'
      source: 'lra-r100-monthly'
      startdate: null
      enddate: null

    - catalog: null
      model: 'ERA5'
      exp: 'era5'
      source: 'monthly'
      startdate: '1990-01-01'
      enddate: '2020-12-31'
      
    - catalog: null
      model: 'CERES'
      exp: 'ebaf-toa41'
      source: 'monthly'
      startdate: '2000-01-01'
      enddate: '2020-12-31'

output:
  outputdir: "./"
  rebuild: true
  filename_keys: ['diagnostic', 'diagnostic_product', 'catalog', 'model', 'exp',
                  'var', 'model_2', 'exp_2', 'catalog_2', 'area', 'time_precision'] # null or, for example,  ['diagnostic', 'catalog', 'model', 'diagnostic_product', 'var']
  save_netcdf: true
  save_pdf: true
  save_png: true
  dpi: 300

diagnostic_attributes:
  variables: ['-tnlwrf', 'tnswrf']
  variable_names: ['Mean top net long-wave radiation flux', 'Mean top net short-wave radiation flux']
