dataset:
  catalog: null #optional, not necessary
  model: ERA5
  exp: era5-hpz3
  source: monthly
  regrid: 'r100'
  atm_vars: ['2t', 'tprate', 'msl', 'ie', 'iews', 'inss', 'tcc', 'tsrwe',
    'tnswrf', 'tnlwrf', 'snswrf', 'snlwrf', 'ishf', 'slhtf',
    'u', 'v', 't', 'q']
  oce_vars: ['tos', 'siconc', 'sos']
  year1: null #if you want to select some specific years, otherwise use the entire dataset
  year2: null

compute:
  numproc: 1

setup:
  interface_file: 'interface_AQUA_climatedt.yaml'
  config_file: 'ecmean_config_climatedt.yaml'
  outputdir: 'output'
  
