datasets:
  - catalog: null
    model: ERA5
    exp: era5-hpz3
    source: monthly
    regrid: r100

output:
  outputdir: 'output'
  rebuild: true
  save_pdf: true
  save_png: true
  dpi: 300

diagnostics:
  ecmean: 
    nprocs: 1
    interface_file: 'interface_AQUA_climatedt.yaml'
    config_file: 'ecmean_config_climatedt.yaml'

    global_mean:
      run: true
      diagnostic_name: 'global_mean'
      atm_vars: ['2t', 'tprate', 'msl', 'ie', 'iews', 'inss', 'tcc', 'tsrwe',
        'tnswrf', 'tnlwrf', 'snswrf', 'snlwrf', 'ishf', 'slhtf',
        'u', 'v', 't', 'q']
      oce_vars: ['tos', 'siconc', 'sos']
      year1: null #if you want to select some specific years, otherwise use the entire dataset
      year2: null

    performance_indices:
      run: true
      diagnostic_name: 'performance_indices'
      atm_vars: ['2t', 'tprate', 'msl', 'ie', 'iews', 'inss', 'tcc', 'tsrwe',
        'tnswrf', 'tnlwrf', 'snswrf', 'snlwrf', 'ishf', 'slhtf',
        'u', 'v', 't', 'q']
      oce_vars: ['tos', 'siconc', 'sos']
      year1: null #if you want to select some specific years, otherwise use the entire 
      year2: null
  